name: Bi-daily EUR-Lex Update

on:
  schedule:
    - cron: '0 10 */2 * *'  # Every other day at 10:00 UTC
  workflow_dispatch:

jobs:
  update-eurlex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 datasets huggingface_hub

    - name: Run EUR-Lex Updater
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python update_eurlex_legislation.py
